eureka:
  client:
    service-url:
      defaultZone: http://localhost:6000/eureka/
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:6411/api/v2/spans
